In [27]:
import torch.nn as nn
import numpy as np
import torch
import pandas as pd



class NN(nn.Module):
    def __init__(self, n_in, n_out):
        
        super(NN, self).__init__()
        self.act = nn.ReLU()
        self.fc1 = nn.Linear(n_in, 2 * n_in)
        self.fc2 = nn.Linear(2 * n_in, 3 * n_in)
        self.fc3 = nn.Linear(3 * n_in, n_out)        
    
    def forward(self, x):
        
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        x = self.act(x)
        x = self.fc3(x)
        
        return x
    


# Computation of the test statistic
#
# X -- array of univariate observations
#
# p -- positive integer (used for basis construction)
#
def compute_test_stat_nn(X, threshold, t_min=20, n_out_min=10, B=10, delta_max=50, n_epochs=200, model=NN):
    
    #X = X.reshape(-1, 1)
    
    # Sample size
    n = X.shape[0]
    
    # Initialization
    T = np.zeros((n, n))
    
    stopping_time = -1
    
    for t in range(t_min, n):
    
        #if (t % 100) == 0:
        #    print('Iteration', t)
            
        for tau in range(np.maximum(t - n_out_min - delta_max, n_out_min), t-n_out_min):
            
            # Initialize neural network
            f = model(n_in=X.shape[1], n_out=1)
            
            # Parameters of the optimizer
            opt = torch.optim.Adam(f.parameters(), lr=1e-1)
            
            X_t = torch.tensor(X[:t, :], dtype=torch.float32, requires_grad=True)
            
            # weights
            W = torch.cat((torch.ones(tau) * (t - tau), torch.ones(t - tau) * tau)).reshape(-1, 1)
            
            # Create "virtual" labels
            Y_t = torch.cat((torch.ones(tau), torch.zeros(t - tau))).reshape(-1, 1)
    
            # Loss function    
            loss_fn = nn.BCEWithLogitsLoss(weight=W)
            
            # Neural network training
            for epoch in range(n_epochs):
                
                loss = loss_fn(f(X_t), Y_t).mean()
                loss.backward()
                opt.step()
                opt.zero_grad()
                
            Z = f(X_t).detach().numpy().reshape(-1)
            
            # Use thresholding to avoid numerical issues
            Z = np.minimum(Z, B)
            Z = np.maximum(Z, -B)
            
            D = np.zeros(t)
            D[:tau] = 2 / (1 + np.exp(-Z[:tau]))
            D[tau:] = 2 / (1 + np.exp(Z[tau:]))
            D = np.log(D)
            
            # Compute statistics for each t
            # and each change point candidate tau
            T[tau, t] = tau * (t - tau) / t * (np.mean(D[:tau]) + np.mean(D[tau:]))
            
        if (np.max(T[:, t]) > threshold):
            
            stopping_time = t
            break
       
    # Array of test statistics
    S = np.max(T[:, :stopping_time + 1], axis=0)
    
    return S, stopping_time


X = pd.read_csv("../data/HAR_NEW/data1.csv").values
change_points = np.load("../data/HAR_NEW/data1.npy")


change_points

array([ 28,  52,  79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304,
       331])

In [ ]:
# Initialization
st_nn = 0
new_st_nn = 0

# the threshold
z_nn = 1

# Initialization of the test statistic
S_nn = np.empty(0)

# Initialization of the list of detected change points
change_points_nn = []


# Initialization of the delays array and
# the false alarms counter
delays_nn = np.empty(0)
current_change_point_ind = 0
false_alarms_nn = 0

data = X.copy()

while new_st_nn >= 0:
    
    # Run the procedure until the moment
    # it reports a change point occurrence
    new_S_nn, new_st_nn = compute_test_stat_nn(data[st_nn + 1:], z_nn, n_epochs=20)
    
    S_nn = np.append(S_nn, new_S_nn)
    
    st_nn += new_st_nn
    change_points_nn += [int(st_nn)]
    
    if(new_st_nn > 0):
        print('Detected change point (neural networks):', st_nn)
        
    if (st_nn < change_points[current_change_point_ind]):
        false_alarms_nn += 1
    
    else:
        delays_nn = np.append(delays_nn, np.array([st_nn - change_points[current_change_point_ind]]), axis=0)
        current_change_point_ind += 1

print('Neural networks. Number of false alarms:', false_alarms_nn, '; average delay:', np.mean(delays_nn),\
     '±', np.std(delays_nn))

Detected change point (neural networks): 39
Detected change point (neural networks): 71
Detected change point (neural networks): 93
Detected change point (neural networks): 124
Detected change point (neural networks): 154
Detected change point (neural networks): 179
Detected change point (neural networks): 241
Detected change point (neural networks): 262
Detected change point (neural networks): 304
Detected change point (neural networks): 332
Neural networks. Number of false alarms: 1 ; average delay: 51.2 ± 34.04937591204867

In [1]:
import wrappers
import test_utils
from test_utils import Tester, run_test_on_dataset

In [4]:
%%time

dir_path = "../data/HAR_NEW/"


models = [wrappers.Contrastive_NN(threshold=1, t_min=20, n_out_min=10, B=10, delta_max=50, n_epochs=10)]
          
          #wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=20, verbose=0, sigma=0.0)
    print(amodel)
    for rep in report:
        display(rep)

[ 28  52  79 126 151 177 203 214 226 238 249 297 304 331]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347]
[30, 56, 77, 100, 123, 144, 165, 186, 209, 234, 256, 283, 304, 325, 324]
[ 24  48  79 106 125 148 169 199 226 252 271]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294]
[23, 48, 70, 92, 113, 134, 155, 178, 202, 225, 246, 271, 270]
[ 22  48  78 107 129 155 181 208 235 265 289]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316]
[23, 45, 77, 99, 120, 141, 162, 186, 209, 234, 258, 279, 300, 299]
[ 28  56  83 110 135 162 196 219 252 275 296]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320]
[23, 45, 66, 87, 114, 137, 159, 180, 201, 223, 250, 279, 303, 302]
[ 28  52  85 115 142 173 203 228 257 284 304]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327]
[24, 46, 68, 91, 113, 138, 159, 181, 210, 232, 255, 278, 302, 325, 324]
[ 31  57  82 112 136 163 193 221 247 276 297]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323]
[27, 51, 79, 100, 121, 143, 164, 189, 211, 232, 255, 276, 301, 300]
[ 28  55  89 117 138 162 188 220 258 284 305]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328]
[23, 44, 65, 86, 107, 128, 150, 171, 194, 221, 246, 267, 289, 311, 310]
[ 37  68 103 129 153 180 222 260 295 320 343]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366]
[28, 50, 71, 93, 114, 137, 158, 179, 208, 229, 251, 272, 293, 320, 345, 344]
[ 44  77 112 144 152 160 168 176 183 191 226 257 293 322 337 361]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368]
[22, 56, 78, 100, 121, 143, 166, 189, 210, 233, 256, 281, 302, 325, 346, 345]
[ 41  71 103 132 142 152 161 170 179 189 222 249 282 309 327 356]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364]
[21, 47, 75, 102, 134, 157, 179, 201, 224, 253, 277, 300, 322, 343, 342]
[ 42  79 120 147 161 175 182 189 221 257 299 324 336 349 355]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360]
[32, 53, 80, 103, 124, 145, 166, 189, 212, 233, 255, 277, 298, 324, 345, 344]
[ 32  56  80 110 134 159 182 204 228 257 280]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302]
[24, 50, 71, 92, 113, 136, 157, 181, 203, 227, 253, 276, 298, 297]
[ 39  75 106 133 155 181 216 246 283 307 330]
[39, 75, 106, 133, 155, 181, 216, 246, 283, 307, 330, 354]
[26, 47, 68, 89, 112, 138, 159, 180, 201, 223, 246, 278, 299, 321, 342, 341]
[ 46  93 137 164 179 196 204 212 256 294 340 365 380 395 402]
[46, 93, 137, 164, 179, 196, 204, 212, 256, 294, 340, 365, 380, 395, 402, 408]
[22, 44, 68, 93, 117, 139, 166, 187, 211, 234, 260, 281, 303, 327, 349, 373, 399, 398]
[ 31  63 100 123 135 149 155 162 195 225 260 283 301]
[31, 63, 100, 123, 135, 149, 155, 162, 195, 225, 260, 283, 301, 321]
[33, 63, 84, 106, 127, 149, 170, 196, 217, 238, 260, 284, 305, 304]
[ 34  72 105 135 144 153 162 170 179 187 222 252 291 320 347]
[34, 72, 105, 135, 144, 153, 162, 170, 179, 187, 222, 252, 291, 320, 347, 372]
[24, 45, 71, 95, 116, 140, 161, 183, 204, 227, 248, 274, 296, 321, 344, 367, 366]
[ 34  68 104 132 159 188 224 258 294 324 343 363 372]
[34, 68, 104, 132, 159, 188, 224, 258, 294, 324, 343, 363, 372, 381]
[21, 42, 71, 100, 121, 144, 166, 187, 210, 234, 257, 282, 303, 325, 346, 368, 367]
[ 38  72 105 141 171 206 243 274 314 352 380]
[38, 72, 105, 141, 171, 206, 243, 274, 314, 352, 380, 409]
[23, 48, 72, 93, 114, 135, 157, 178, 199, 221, 256, 279, 300, 321, 344, 365, 386, 385]
[ 39  83 117 145 170 198 234 268 310 341 358 376 384]
[39, 83, 117, 145, 170, 198, 234, 268, 310, 341, 358, 376, 384, 392]
[30, 51, 77, 101, 122, 146, 167, 189, 210, 233, 255, 276, 300, 321, 343, 364, 386, 385]
[ 37  74 110 138 160 185 229 262 300 329 351]
[37, 74, 110, 138, 160, 185, 229, 262, 300, 329, 351, 376]
[27, 48, 69, 93, 115, 140, 162, 184, 214, 235, 259, 280, 301, 333, 355, 354]
[ 44  87 129 157 165 174 190 209 245 274 312 338 360]
[44, 87, 129, 157, 165, 174, 190, 209, 245, 274, 312, 338, 360, 382]
[23, 44, 66, 89, 110, 132, 154, 179, 200, 221, 246, 267, 289, 310, 336, 363, 362]
[ 32  60 100 126 150 175 209 241 270 297 321]
[32, 60, 100, 126, 150, 175, 209, 241, 270, 297, 321, 344]
[21, 43, 66, 88, 109, 132, 154, 175, 196, 220, 244, 269, 298, 320, 341, 340]
[ 32  58  88 119 142 176 206 232 264 291 317]
[32, 58, 88, 119, 142, 176, 206, 232, 264, 291, 317, 341]
[23, 44, 65, 87, 110, 131, 152, 175, 198, 219, 240, 262, 288, 310, 332, 331]
[ 28  60  98 131 154 178 189 200 232 262 294 326 354]
[28, 60, 98, 131, 154, 178, 189, 200, 232, 262, 294, 326, 354, 383]
[29, 50, 71, 92, 113, 135, 156, 177, 198, 220, 241, 262, 284, 306, 330, 355, 380, 379]
[ 29  53  83 114 137 165 193 219 243 272 294]
[29, 53, 83, 114, 137, 165, 193, 219, 243, 272, 294, 317]
[23, 49, 79, 100, 121, 143, 164, 186, 207, 228, 251, 272, 297, 296]
[ 29  52  80 110 135 160 188 209 233 259 281]
[29, 52, 80, 110, 135, 160, 188, 209, 233, 259, 281, 302]
[22, 47, 70, 91, 112, 136, 158, 180, 203, 230, 251, 273, 295, 294]
[ 31  60  88 117 141 167 194 220 249 277 301]
[31, 60, 88, 117, 141, 167, 194, 220, 249, 277, 301, 325]
[22, 43, 64, 86, 107, 130, 151, 172, 203, 225, 248, 272, 300, 323, 322]
[ 29  55  82 111 136 162 187 209 234 262 284]
[29, 55, 82, 111, 136, 162, 187, 209, 234, 262, 284, 308]
[28, 49, 72, 93, 114, 135, 156, 178, 200, 223, 244, 265, 286, 285]
[ 23  45  70  94 114 135 167 191 220 244 262]
[23, 45, 70, 94, 114, 135, 167, 191, 220, 244, 262, 281]
[21, 42, 69, 93, 116, 137, 159, 180, 201, 225, 248, 269, 268]
[ 23  48  72  98 105 115 121 129 137 145 168 193 219 245 259 282]
[23, 48, 72, 98, 105, 115, 121, 129, 137, 145, 168, 193, 219, 245, 259, 282, 288]
[26, 47, 71, 96, 117, 138, 159, 181, 203, 224, 245, 266, 265]
<wrappers.Contrastive_NN object at 0x75e1e1e47980>

                   0         1          2          3
F1          0.838492  0.083703   0.666667   0.960000
AUC         0.846936  0.083462   0.667279   0.961538
FP          3.433333  1.633345   1.000000   7.000000
DD          6.459123  1.191855   4.428571   9.222222
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.649862  0.052342   0.513629   0.739708
Runtime    17.634074  6.205876   8.120794  34.378712

                   0         1          2          3
F1          0.857854  0.064293   0.705882   0.960000
AUC         0.866532  0.064043   0.708333   0.961538
FP          0.333333  0.711159   0.000000   3.000000
DD          6.459123  1.191855   4.428571   9.222222
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.649862  0.052342   0.513629   0.739708
Runtime    17.634074  6.205876   8.120794  34.378712

                   0         1          2          3
F1          0.868362  0.052921   0.764706   0.960000
AUC         0.877089  0.051557   0.767361   0.961538
FP          0.000000  0.000000   0.000000   0.000000
DD          6.459123  1.191855   4.428571   9.222222
Threshold  30.000000  0.000000  30.000000  30.000000
Covering    0.649862  0.052342   0.513629   0.739708
Runtime    17.634074  6.205876   8.120794  34.378712

                   0         1          2          3
F1          0.873739  0.049023   0.764706   0.960000
AUC         0.882567  0.047451   0.767361   0.961538
FP          0.000000  0.000000   0.000000   0.000000
DD          6.459123  1.191855   4.428571   9.222222
Threshold  40.000000  0.000000  40.000000  40.000000
Covering    0.649862  0.052342   0.513629   0.739708
Runtime    17.634074  6.205876   8.120794  34.378712

                   0         1          2          3
F1          0.878112  0.049918   0.764706   0.960000
AUC         0.886960  0.047923   0.767361   0.961538
FP          0.000000  0.000000   0.000000   0.000000
DD          6.459123  1.191855   4.428571   9.222222
Threshold  50.000000  0.000000  50.000000  50.000000
Covering    0.649862  0.052342   0.513629   0.739708
Runtime    17.634074  6.205876   8.120794  34.378712

CPU times: user 2h 10s, sys: 9min 59s, total: 2h 10min 9s
Wall time: 8min 50s

In [7]:
%%time

dir_path = "../data/MNIST_SWCPD/"


models = [wrappers.Contrastive_NN(threshold=15, t_min=100, n_out_min=10, B=10, delta_max=50, n_epochs=5)]
          
          #wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=20, verbose=0, sigma=0.0)
    print(amodel)
    for rep in report:
        display(rep)

[200 400]
[200, 400, 600]

KeyboardInterrupt: